source 'https://cdn.cocoapods.org/'
require 'fileutils'

# Uncomment the next line to define a global platform for your project
platform :osx, '11.0'
workspace 'eqMac.xcworkspace'
use_frameworks!

post_install do |installer|
  # AMCoreAudio 3.4 imports a CoreAudio submodule removed from modern SDKs.
  # The same declarations are available from the parent CoreAudio module.
  Dir.glob(File.join(__dir__, 'Pods/AMCoreAudio/Source/**/*.swift')).each do |path|
    source = File.read(path)
    updated = source
      .gsub('import CoreAudio.AudioHardwareBase', 'import CoreAudio')
      .gsub(
        'kAudioHardwareServiceDeviceProperty_VirtualMasterVolume',
        'kAudioHardwareServiceDeviceProperty_VirtualMainVolume'
      )
      .gsub(
        'kAudioHardwareServiceDeviceProperty_VirtualMasterBalance',
        'kAudioHardwareServiceDeviceProperty_VirtualMainBalance'
      )
    next if source == updated

    FileUtils.chmod('u+w', path)
    File.write(path, updated)
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '11.0'
    end
  end
end

# ignore all warnings from all pods
inhibit_all_warnings!

def shared_pods
  pod 'STPrivilegedTask', :git => 'https://github.com/sveinbjornt/STPrivilegedTask.git', :commit => 'fdca677c77adb166a2be4c5ea9c7580a738c49c9'
end

project 'app/eqMac.xcodeproj'

target 'eqMac' do
  project 'app/eqMac.xcodeproj'

  pod 'SwiftHTTP', '~> 3.0'
  pod 'AMCoreAudio', :podspec => 'AMCoreAudio.podspec'
  pod 'WebViewJavascriptBridge', '~> 6.0'
#  pod 'ReachabilitySwift'
  pod 'ReSwift', '~> 6.1'
  pod 'EmitterKit', '~> 5.2.2'
  pod 'SwiftyJSON', '~> 4.2'
  pod 'SwiftyUserDefaults', '4.0'
  pod 'KeychainSwift', '~> 13.0'
  pod 'Zip', :git => 'https://github.com/bitgapp/Zip.git'
  shared_pods

end
